# Concatenate the copied Cantilever Beam Designer engine (engines/cantilever-src)
# into ONE isolated-namespace bundle: engines/cantilever-design-engine.js
# Everything runs inside a single IIFE so only globalThis.CANTILEVER_DESIGN leaks.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$src  = Join-Path $root 'engines\cantilever-src'
$out  = Join-Path $root 'engines\cantilever-design-engine.js'
$utf8 = [Text.UTF8Encoding]::new($false)

# Load order: section data -> headless shim -> section helpers -> solver ->
# EC3/BS checks -> orchestration -> Mcr-eigen patch -> driver.
$files = @(
  'sections\ub-section-data.js',
  'sections\uc-section-data.js',
  'sections\pfc-section-data.js',
  'sections\rhs-section-data.js',
  'sections\shs-section-data.js',
  '00-headless-shim.js',
  '02-section-data.js',
  '01-computation-engine.js',
  'checks\eurocode-checks.js',
  'checks\bs5950-checks.js',
  '04-checks.js',
  '08-mcr-eigen-patch.js',
  '99-driver.js'
)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('/* AUTO-GENERATED by build-cantilever-engine.ps1 - do not edit by hand.')
[void]$sb.AppendLine('   Isolated bundle of the Cantilever Beam Designer engine for the rack. */')
[void]$sb.AppendLine('(function(){')
foreach ($f in $files) {
  $path = Join-Path $src $f
  if (-not (Test-Path $path)) { throw "Missing engine file: $f" }
  [void]$sb.AppendLine("/* ===== $f ===== */")
  [void]$sb.AppendLine(([IO.File]::ReadAllText($path, $utf8)).Trim())
  [void]$sb.AppendLine('')
}
[void]$sb.AppendLine('})();')

[IO.File]::WriteAllText($out, $sb.ToString(), $utf8)
Write-Host "Built $out ($([math]::Round((Get-Item $out).Length/1024)) KB)"
